version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      MONGO_INITDB_DATABASE: "personalWebsite"
    ports:
      - 27017:27017
    volumes:
      - ./database/init.d:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/

  personalwebsite_backend:
    image: personalwebsite_backend:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mongodb://appUserAdmin:secret@mongodb:27017/personalWebsite
  
  personalwebsite_frontend:
    image: personalwebsite_frontend:latest
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules